library(QDNAseq)
bins=getBinAnnotations(binSize=1000,genome='hg38')
readCounts=binReadCounts(bins, bamfiles = c("M_sample1.bam","M_sample2.bam"))
readCountsFiltered=applyFilters(readCounts,residual=T,blacklist=T)
readCountsFiltered=estimateCorrection(readCountsFiltered)
copyNumbers=correctBins(readCountsFiltered)
copyNumbersNormalized=normalizeBins(copyNumbers)
copyNumbersSmooth=smoothOutlierBins(copyNumbersNormalized)
copyNumbersSegmented=segmentBins(copyNumbersSmooth,transformFun="sqrt")
copyNumbersSegmented=normalizeSegmentedBins(copyNumbersSegmented)
copyNumbersCalled=callBins(copyNumbersSegmented)
pdf("copynumber.1000kb.pdf")
plot(copyNumbersSegmented)
plot(copyNumbersCalled)
dev.off()
exportBins(copyNumbersSmooth,file="copyNumbersSmooth.1000kb.txt")
exportBins(copyNumbersCalled,file="copyNumbersCalled.1000kb.%s.txt",format="seg")
